### ISSUE TITLE
Broken links on the site

### ISSUE THREAD

**Issue by tzach** [scylladb/seastar-website#13]
For example
Link from http://seastar.io/seastar-applications/ to http://seastar.io/memcached/

**Comment by juliaangell** [comment]
@rusher81572 did you see this?

**Comment by rusher81572** [comment]
Thanks @juliaangell  I did not see this notification. @tzach Where should that link to? I do not see any pages done for Memcached.

Maybe this? https://github.com/scylladb/seastar/wiki/Memcached-Benchmark

**Comment by jvanz** [comment]
There is a broken link for the documentation in the "Getting Started with Seastar" section of the home page. There is a pull request fixing this... but I guess this repo follows the seastart project stanards of send patches via e-mail, am I right?
