### ISSUE TITLE
Wrong link to Google Group

### ISSUE THREAD

**Issue by tzach** [scylladb/seastar-website#16]
On http://seastar.io/ section Getting Started with Seastar
seastar-dev link to the wrong URL: https://groups.google.com/forum/?hl=en#!forum-dev
should be https://groups.google.com/forum/#!forum/seastar-dev

**Comment by rusher81572** [comment]
Committed the changes. May you please verify that it is good?

**Comment by tzach** [comment]
looks good. Thanks

**Comment by tzach** [comment]
close with https://github.com/scylladb/seastar-website/commit/aba8c906f6aaf6ef8e18cb3bd5df6c666d5bd366
